### ISSUE TITLE
Auth in server side rendering

### ISSUE THREAD

**Issue by guido4000** [supertokens/supertokens-nextjs-demo#2]
It would be great to have an example on how to use auth for getServerSideProps.

**Comment by kant01ne** [comment]
Hey @guido4000! 
Thanks for the issue :) I'll provide an example soonish.

Since `getServerSideProps` would essentially be fetching data from backend, you can use https://supertokens.io/docs/emailpassword/quick-setup/backend#6-add-session-verification as an example of how to validate a session on the server side before returning user specific information.

**Comment by kant01ne** [comment]
I took a look at how to use getServerSideProps, and I came up with a solution that would only partially work for now though. 

The reason being that SuperTokens refreshes the user session regularly (By default every one hour) and that is done by our front end SDK (https://github.com/supertokens/supertokens-website/), which in turns does bunch of things that can not be done server side, such as synchronising the session between different active tabs etc...

My understanding of SSR is that you would use it to render static content first, and would use regular API calls to fetch user data from the front end. 

Can you give me more info on what would you need authenticated `getServerSideProps` for @guido4000 ?

**Comment by guido4000** [comment]
@NkxxkN I want to render a dashboard with a lot of numbers which need to be updated every second. So I want to get the numbers server side to show them on page load and then use SWR/ReactQuery client side to keep them updated.

**Comment by kant01ne** [comment]
Hey @guido, thanks for letting me know about your use case. It seems that this would be a nice to have optimisation for you to make your data loading faster but that require quite a lot of changes for us which we are not going to prioritise at the moment. 

You always have the option of verifying the session on the client side and load empty states for your dashboard while you are fetching the data.

**Comment by guido4000** [comment]
Ok, we will see a lot of developments in the server side rendering space in any case as the React team is actively working on server components.

https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html

**Comment by rishabhpoddar** [comment]
Closing this issue since we have an example of this now: https://supertokens.io/docs/thirdpartyemailpassword/nextjs/session-verification/in-ssr
